FROM nginx:1.19-alpine

COPY nginx.conf /etc/nginx/nginx.conf 
COPY 404.png /expert_seas/images/404.png
COPY expert_seas_icon.png /expert_seas/images/expert_seas_icon.png
COPY 404.html /expert_seas/404.html
