version: '3'

volumes:
  es_storage:

services:

  nginx:
    build: ./nginx
    ports:
     - "8080:80"
    volumes:
      - es_storage:/expert_seas/images


  main_node:
    build: ./main_node
    expose:
     - "8080"
    volumes:
      - es_storage:/expert_seas/images
    command: "/DARLMID/startup.sh"
    environment:
      - MAIN_NODE_URL
      - REDIS_HOST
      - REDIS_PASSWORD
      - POSTGRES_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - R_USERNAME
      - R_PASSWORD
      - RW_USERNAME
      - RW_PASSWORD

  redis:
    image: 'redis:6-alpine'
    container_name: redis
    environment:
        - REDIS_PASSWORD
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
        - '6379:6379'

  db:
    image: postgres:13-alpine
    restart: always
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
